export const UPLOAD_PRODUCT_LIST = 'UPLOAD_PRODUCT_LIST'
export const SORT_LIST_ABC = 'SORT_LIST_ABC'
export const SORT_LIST_123 = 'SORT_LIST_123'

export const STATE_CURRENCY_EUR = 'STATE_CURRENCY_EUR'
export const STATE_CURRENCY_CAD = 'STATE_CURRENCY_CAD'
export const STATE_CURRENCY_USD = 'STATE_CURRENCY_USD'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
