export const UPDATE_FIRST_NAME_FIELD = 'FIRST_NAME_FIELD'
export const UPDATE_LAST_NAME_FIELD = 'LAST_NAME_FIELD'
export const UPDATE_EMAIL_FIELD = 'UPDATE_EMAIL_FIELD'
export const UPDATE_PASSWORD_FIELD = 'PASSWORD_FIELD'
export const LOGIN = 'LOGIN'

export const UPLOAD_PRODUCT_LIST = 'UPLOAD_PRODUCT_LIST'
export const SORT_LIST_ABC = 'SORT_LIST_ABC'
export const SORT_LIST_123 = 'SORT_LIST_123'
