export const UPDATE_FIRST_NAME_FIELD = 'FIRST_NAME_FIELD'
export const UPDATE_LAST_NAME_FIELD = 'LAST_NAME_FIELD'
export const UPDATE_EMAIL_FIELD = 'UPDATE_EMAIL_FIELD'
export const UPDATE_PASSWORD_FIELD = 'PASSWORD_FIELD'
export const SET_MESSAGE_FOR_LOGIN_FORM = 'SET_MESSAGE_FOR_LOGIN_FORM'
export const LOGIN = 'LOGIN'

export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE'
